[package]
name = "xtask"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
#proc-macro2 = "1.0.49"
quote = "1.0.23"

[dependencies.syn]
version = "1.0.107"
features = ["full", "parsing", "extra-traits", "visit-mut"]
