[package]
name = "main"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
solution_01 = { path = "../solution_01" }
io = { path = "../io" }
common = { path = "../common" }
